# Generated by Django 4.1.2 on 2023-01-05 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "reservations",
            "0005_alter_customsortorder_id_alter_nrequirements_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="sort_order",
        ),
        migrations.AlterField(
            model_name="reservableset",
            name="name",
            field=models.CharField(
                help_text="ReservableSet model is used to group common reservables together.",
                max_length=255,
                verbose_name="ReservableSet name",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end",
            field=models.DateTimeField(verbose_name="An end time of the reservation"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="owners",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="The reservation owners"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reason",
            field=models.CharField(
                max_length=255, verbose_name="A reason for the reservation."
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservables",
            field=models.ManyToManyField(
                related_name="reservations",
                to="reservations.reservable",
                verbose_name="reservables",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start",
            field=models.DateTimeField(verbose_name="A start time of the reservation"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="resource",
            name="type",
            field=models.CharField(
                help_text="The type of the resource.", max_length=255
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=models.Q(("start__lt", models.F("end"))),
                name="reservations_reservation_start_before_end",
            ),
        ),
        migrations.DeleteModel(
            name="CustomSortOrder",
        ),
    ]
