# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_auto_20170302_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customsortorder",
            name="order",
            field=models.TextField(
                default="",
                help_text="Comma separated List of reservable ids that determines its sort order",
            ),
        ),
    ]
