# Generated by Django 5.2.8 on 2026-02-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_add_external_id_to_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nrequirements',
            options={'verbose_name': 'countable requirement', 'verbose_name_plural': 'countable requirements'},
        ),
        migrations.AlterModelOptions(
            name='nresources',
            options={'verbose_name': 'countable resource', 'verbose_name_plural': 'countable resources'},
        ),
        migrations.AlterModelOptions(
            name='reservable',
            options={'permissions': (('reserve', 'Create a reservation using this reservable'), ('double_reserve', 'Create an overlapping reservation'), ('manage_reservations', 'Manage reservations using this reservable')), 'verbose_name': 'reservable', 'verbose_name_plural': 'reservables'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
    ]
