# Generated by Django 5.2.8 on 2026-05-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_alter_nrequirements_options_alter_nresources_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservable",
            options={
                "ordering": ["order"],
                "permissions": (
                    ("reserve", "Create a reservation using this reservable"),
                    ("double_reserve", "Create an overlapping reservation"),
                    ("manage_reservations", "Manage reservations using this reservable"),
                ),
                "verbose_name": "reservable",
                "verbose_name_plural": "reservables",
            },
        ),
        migrations.AddField(
            model_name="reservable",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
