# Generated by Django 5.2.8 on 2026-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0010_add_reservation_timestamps"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservableset",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="reservableset",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
