# Generated by Django 5.2.8 on 2026-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0011_reservableset_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservableType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("hidden", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "reservable type",
                "verbose_name_plural": "reservable types",
                "ordering": ["order"],
            },
        ),
    ]
