# Generated by Django 5.2.8 on 2026-09-02 07:23

import django.db.models.deletion
from django.db import migrations, models


def link_reservable_types(apps, schema_editor):
    Reservable = apps.get_model("reservations", "Reservable")
    ReservableType = apps.get_model("reservations", "ReservableType")

    slugs = Reservable.objects.order_by().values_list("type", flat=True).distinct()
    for order, slug in enumerate(slugs):
        reservable_type, _ = ReservableType.objects.get_or_create(
            slug=slug, defaults={"display_name": slug.title(), "order": order}
        )
        Reservable.objects.filter(type=slug).update(type_new=reservable_type)


def unlink_reservable_types(apps, schema_editor):
    Reservable = apps.get_model("reservations", "Reservable")

    for reservable in Reservable.objects.select_related("type_new"):
        reservable.type = reservable.type_new.slug if reservable.type_new_id else ""
        reservable.save(update_fields=["type"])


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_reservabletype"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservable",
            name="type_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservables",
                to="reservations.reservabletype",
            ),
        ),
        migrations.RunPython(link_reservable_types, unlink_reservable_types),
        migrations.RemoveField(
            model_name="reservable",
            name="type",
        ),
        migrations.RenameField(
            model_name="reservable",
            old_name="type_new",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="reservable",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservables",
                to="reservations.reservabletype",
            ),
        ),
    ]
